// Exact source-bone map for the Quaternius Universal Animation Library.
// Source keyframes remain immutable; this file only maps donor joints to Character 2027 semantics.
export const QUATERNIUS_RIG_MAP = {
  "DEF-hips": "hips",
  "DEF-spine.001": "spine",
  "DEF-spine.002": "chest",
  "DEF-spine.003": "upperChest",
  "DEF-neck": "neck",
  "DEF-head": "head",
  "DEF-shoulder.L": "leftShoulder",
  "DEF-upper_arm.L": "leftUpperArm",
  "DEF-forearm.L": "leftLowerArm",
  "DEF-hand.L": "leftHand",
  "DEF-shoulder.R": "rightShoulder",
  "DEF-upper_arm.R": "rightUpperArm",
  "DEF-forearm.R": "rightLowerArm",
  "DEF-hand.R": "rightHand",
  "DEF-thigh.L": "leftUpperLeg",
  "DEF-shin.L": "leftLowerLeg",
  "DEF-foot.L": "leftFoot",
  "DEF-toe.L": "leftToes",
  "DEF-thigh.R": "rightUpperLeg",
  "DEF-shin.R": "rightLowerLeg",
  "DEF-foot.R": "rightFoot",
  "DEF-toe.R": "rightToes",
  "DEF-thumb.01.L": "leftThumbMetacarpal",
  "DEF-thumb.02.L": "leftThumbProximal",
  "DEF-thumb.03.L": "leftThumbDistal",
  "DEF-f_index.01.L": "leftIndexProximal",
  "DEF-f_index.02.L": "leftIndexIntermediate",
  "DEF-f_index.03.L": "leftIndexDistal",
  "DEF-f_middle.01.L": "leftMiddleProximal",
  "DEF-f_middle.02.L": "leftMiddleIntermediate",
  "DEF-f_middle.03.L": "leftMiddleDistal",
  "DEF-f_ring.01.L": "leftRingProximal",
  "DEF-f_ring.02.L": "leftRingIntermediate",
  "DEF-f_ring.03.L": "leftRingDistal",
  "DEF-f_pinky.01.L": "leftLittleProximal",
  "DEF-f_pinky.02.L": "leftLittleIntermediate",
  "DEF-f_pinky.03.L": "leftLittleDistal",
  "DEF-thumb.01.R": "rightThumbMetacarpal",
  "DEF-thumb.02.R": "rightThumbProximal",
  "DEF-thumb.03.R": "rightThumbDistal",
  "DEF-f_index.01.R": "rightIndexProximal",
  "DEF-f_index.02.R": "rightIndexIntermediate",
  "DEF-f_index.03.R": "rightIndexDistal",
  "DEF-f_middle.01.R": "rightMiddleProximal",
  "DEF-f_middle.02.R": "rightMiddleIntermediate",
  "DEF-f_middle.03.R": "rightMiddleDistal",
  "DEF-f_ring.01.R": "rightRingProximal",
  "DEF-f_ring.02.R": "rightRingIntermediate",
  "DEF-f_ring.03.R": "rightRingDistal",
  "DEF-f_pinky.01.R": "rightLittleProximal",
  "DEF-f_pinky.02.R": "rightLittleIntermediate",
  "DEF-f_pinky.03.R": "rightLittleDistal",
}

export const TARGET_BONE_ALIASES = {
  hips: ["hips", "Hips", "mixamorigHips", "mixamorig:Hips", "J_Bip_C_Hips"],
  spine: ["spine", "Spine", "mixamorigSpine", "mixamorig:Spine", "J_Bip_C_Spine"],
  chest: ["chest", "Chest", "mixamorigSpine1", "mixamorig:Spine1", "J_Bip_C_Chest"],
  upperChest: ["upperChest", "UpperChest", "mixamorigSpine2", "mixamorig:Spine2", "J_Bip_C_UpperChest"],
  neck: ["neck", "Neck", "mixamorigNeck", "mixamorig:Neck", "J_Bip_C_Neck"],
  head: ["head", "Head", "mixamorigHead", "mixamorig:Head", "J_Bip_C_Head"],
  leftShoulder: ["leftShoulder", "LeftShoulder", "mixamorigLeftShoulder", "mixamorig:LeftShoulder", "J_Bip_L_Shoulder"],
  leftUpperArm: ["leftUpperArm", "LeftArm", "mixamorigLeftArm", "mixamorig:LeftArm", "J_Bip_L_UpperArm"],
  leftLowerArm: ["leftLowerArm", "LeftForeArm", "mixamorigLeftForeArm", "mixamorig:LeftForeArm", "J_Bip_L_LowerArm"],
  leftHand: ["leftHand", "LeftHand", "mixamorigLeftHand", "mixamorig:LeftHand", "J_Bip_L_Hand"],
  rightShoulder: ["rightShoulder", "RightShoulder", "mixamorigRightShoulder", "mixamorig:RightShoulder", "J_Bip_R_Shoulder"],
  rightUpperArm: ["rightUpperArm", "RightArm", "mixamorigRightArm", "mixamorig:RightArm", "J_Bip_R_UpperArm"],
  rightLowerArm: ["rightLowerArm", "RightForeArm", "mixamorigRightForeArm", "mixamorig:RightForeArm", "J_Bip_R_LowerArm"],
  rightHand: ["rightHand", "RightHand", "mixamorigRightHand", "mixamorig:RightHand", "J_Bip_R_Hand"],
  leftUpperLeg: ["leftUpperLeg", "LeftUpLeg", "mixamorigLeftUpLeg", "mixamorig:LeftUpLeg", "J_Bip_L_UpperLeg"],
  leftLowerLeg: ["leftLowerLeg", "LeftLeg", "mixamorigLeftLeg", "mixamorig:LeftLeg", "J_Bip_L_LowerLeg"],
  leftFoot: ["leftFoot", "LeftFoot", "mixamorigLeftFoot", "mixamorig:LeftFoot", "J_Bip_L_Foot"],
  leftToes: ["leftToes", "LeftToeBase", "mixamorigLeftToeBase", "mixamorig:LeftToeBase", "J_Bip_L_ToeBase"],
  rightUpperLeg: ["rightUpperLeg", "RightUpLeg", "mixamorigRightUpLeg", "mixamorig:RightUpLeg", "J_Bip_R_UpperLeg"],
  rightLowerLeg: ["rightLowerLeg", "RightLeg", "mixamorigRightLeg", "mixamorig:RightLeg", "J_Bip_R_LowerLeg"],
  rightFoot: ["rightFoot", "RightFoot", "mixamorigRightFoot", "mixamorig:RightFoot", "J_Bip_R_Foot"],
  rightToes: ["rightToes", "RightToeBase", "mixamorigRightToeBase", "mixamorig:RightToeBase", "J_Bip_R_ToeBase"],
}

export function findTargetBone(targetRoot, canonicalName) {
  const aliases = TARGET_BONE_ALIASES[canonicalName] || [canonicalName]
  for (const alias of aliases) {
    const node = targetRoot?.getObjectByName(alias)
    if (node?.isBone) return node
  }
  return null
}
